export const ADVERT_LIST_LOAD_REQUEST = 'ADVERT_LIST_LOAD_REQUEST';
export const ADVERT_LIST_LOAD = 'ADVERT_LIST_LOAD';
export const ADVERT_LIST_LOAD_ERROR = 'ADVERT_LIST_LOAD_ERROR';

export const ADVERT_DETAIL_LOAD_REQUEST = 'ADVERT_DETAIL_LOAD_REQUEST';
export const ADVERT_DETAIL_LOAD = 'ADVERT_DETAIL_LOAD';
export const ADVERT_DETAIL_LOAD_ERROR = 'ADVERT_DETAIL_LOAD_ERROR';
