# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:20
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import helpers.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Если оставить пустым - заполнится автоматом', max_length=255, populate_from='title', unique=True)),
                ('image', models.ImageField(max_length=255, upload_to=helpers.utils.generate_upload_name, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
